---
editor_options: 
  markdown: 
    wrap: sentence
---

# References

Ada, Sila, Nadia Abou Nabout, and Elea McDonnell Feit (2022), "Context Information can Increase Revenue in Ad Auctions: Evidence from a Policy Change," Journal of Marketing Research, forthcoming.

Aguirre, E., D. Mahr, D. Grewal, K. D. Ruyter, and M.
Wetzels (2015), "Unraveling the Personalization Paradox: The Effect of Information Collection and Trust-Building Strategies on Online Advertisement Effectiveness," Journal of Retailing, 91 (1), 34--59.

Athey, Susan, Christian Catalini, and Catherine Tucker (2017), "The Digital Privacy Paradox: Small Money, Small Costs, Small Talk." Working Paper.

Beke, Frank T., Felix Eggers, and Peter C. Verhoef (2018), "Consumer Informational Privacy: Current Knowledge and Research Directions," Foundations and Trends in Marketing, 11 (1), 1-71.

Bleier, Alexander and Maik Eisenbeiss (2015), "Personalized Online Advertising Effectiveness: The Interplay of What, When, and Where," Marketing Science, 34 (5), 669-88.

Bleier, Alexander, Avi Goldfarb, and Catherine.
E. Tucker (2020), "Consumer Privacy and the Future of Data-Based Innovation and Marketing," International Journal of Research in Marketing, 37 (3), 466-80.

Board, Simon (2009), "Revealing Information in Auctions: the Allocation Effect," Economic Theory, 38 (1), 125-35.

Boerman, Sophie C., Sanne Kruikemeier, and Frederik J. Zuiderveen Borgesius (2017), "Online Behavioral Advertising: A Literature Review and Research Agenda," Journal of Advertising, 46 (3), 363-76.

Celis, L. Elisa, Sayash Kapoor, Farnood Salehi, and Nisheeth K. Vishnoi (2019), "Controlling Polarization in Personalization: An Algorithmic Framework," in FAT\* '19: Proceedings of the Conference on Fairness, Accountability, and Transparency.

Chen, Jianqing and Jan Stallaert (2014), "An Economic Analysis of Online Advertising Using Behavioral Targeting," MIS Quarterly, 38 (2), 429-49.

Cristal, Gergory (2014), Ad Serving Technology.
Understand the Marketing Revelation that Commercialized the Internet.
Self-Publishing.

Datenschutzbehörde (2019), "Bescheid: Datenschutzbehörde entscheidet über die Datenschutzbeschwerde des Peter A\*\*\* (Beschwerdeführer) vom 04. Juni 2018 gegen die N\*Mediengesellschaft m.b.H. (Beschwerdegegnerin) wegen Verletzung im Recht auf Geheimhaltung," in DSB-D122.974/0001-DSB/2019 vom 20.8.2019.
<https://www.ris.bka.gv.at/Dokumente/Dsk/DSBT_20190820_DSB_D122_974_0001_DSB_2019_00/DSBT_20190820_DSB_D122_974_0001_DSB_2019_00.html>.

Degeling, M., C. Utz, C. Lentzsch, H. Hosseini, F. Schaub, and Holz; T.
(2019), "We Value Your Privacy ... Now Take Some Cookies: Measuring the GDPR's Impact on Web Privacy," in 26th Annual Network and Distributed System Security Symposium, Internet Society.

Enge, Eric (2021), "Mobile vs. Desktop Usage in 2020," [available at <https://www.perficient.com/insights/research-hub/mobile-vs-desktop-usage>].

European Commission (2021), "Digital Markets Act: Ensuring Fair and Open Digital Markets," [available at <https://ec.europa.eu/commission/presscorner/detail/en/QANDA_20_2349>].

European Data Protection Board (2020), "Guidelines 05 / 2020 on Consent under Regulation 2016/679 (Version 1.1, Adopted on 4 May, 2020)." <https://edpb.europa.eu/sites/default/files/files/file1/edpb_guidelines_202005_consent_en.pdf>.

Gradow, Lisa and Ramona Greiner (2021), Quick Guide Consent-Management.
Einwilligungen marketingoptimiert und DSGVO-konform einholen, verwalten und dokumentieren.
Heidelberg: SpringerGabler.

Gross, Ralph and Alessandro Acquisti (2005), "Information Revelation and Privacy in Online Social Networks." WPES '05: Proceedings of the 2005 ACM Workshop on Privacy in the Electronic Society.

Ho, Shuk Ying and David Bodoff (2014), "The Effects of Web Personalization on User Attitude and Behavior," MIS Quarterly, 38 (2), 487-520.

Hsiao, Sissie (2020), "How our Display Buying Platforms Share Revenue with Publishers," in Blog Post on Google Ad Manager.
<https://blog.google/products/admanager/display-buying-share-revenue-publishers/>.

IAB (2020), "AdEx Benchmark 2019." Report.

IAB (2021), "Internet Advertising Revenue Report. Full Year 2020 Results." Report.

IAB Europe (2021a), "ePrivacy Regulation: The Key Questions Answered," [available at <https://datadrivenadvertising.eu/impact-of-eprivacy-regulation/>].

IAB Europe (2021b), "IAB Europe, TCF and NOYB's War On Cookie Banners," [available at <https://iabeurope.eu/blog/iab-europe-tcf-and-noybs-war-on-cookie-banners>].

Information Commissioner's Office (2019), "Update Report into Adtech and Real Time Bidding."

Janssen, Rebecca, Reinhold Kesler, Michael Kummer, and Joel Waldfogel (2021), "GDPR and the Lost Generation of Innovative Apps," Working Paper.

Johnson, Garrett A., Scott Shriver, and Shaoyin Du (2020), "Consumer Privacy Choice in Online Advertising: Who Opts Out and at What Cost to Industry?," Marketing Science, 39 (1), 33-51.

Jürgensmeier, Lukas and Bernd Skiera (2022), "Measuring Fair Competition on Digital Platforms," Working Paper.

Kosorin, Dominik (2016), Introduction to Programmatic Advertising.
Self-Publishing.

Kraft, Lennart, Klaus M. Miller, and Bernd Skiera (2021), "Privacy and the Prevalence of Inconsistencies in Third-Party Consumer Profiling on the Internet," Working Paper.

Kulyk, Oksana, Nina Gerber, Annika Hilt, and Melanie Volkamer (2020), "Has the GDPR Hype Affected Users' Reaction to Cookie Disclaimers? ," Journal of Cyber Security, 6 (1), 1-14.

Lambrecht, Anja and Catherine Tucker (2013), "When Does Retargeting Work? Timing Information Specificity," Journal of Marketing Research, 50 (5), 561-76.

Laub, René, Klaus M. Miller, and Bernd Skiera (2022), "The Economic Value of User Tracking and Behavioral Targeting for Publishers," Working Paper, Goethe University Frankfurt.

Lee, Kuang-Chih, Ali Jalali, and Ali Dasdan (2013), "Real Time Bid Optimization with Smooth Budget Delivery in Online Advertising." Proceedings of the 19th ACM Conference on Knowledge Discovery and Data Mining (KDD'13).

Levin, Jonathan and Paul Milgrom (2010), "Online Advertising: Heterogeneity and Conflation in Market Design," American Economic Review: Papers & Proceedings, 100 (May), 603-07.

Lischka, Helena Maria and Peter Kenning (2020), Need for Digital Privacy -- Ansatzpunkt der marktorientierten Unternehmensführung für Innovationen in der digitalen Wirtschaft!?:
Springer.

Lukic, Karlo, Klaus M. Miller, and Bernd Skiera (2022), "The Impact of the General Data Protection Regulation (GDPR) on Online Tracking," Working Paper, Goethe University Frankfurt.

Luma Partners (2021), "Display Lumascape." <https://lumapartners.com/content/lumascapes/display-ad-tech-lumascape/>.

Martin, Kelly D.
and Patrick E. Murphy (2017), "The Role of Data Privacy in Marketing," Journal of the Academy of Marketing Science, 45 (2), 135--55.

Miller, Klaus M.
and Bernd Skiera (2022), "Economic Consequences of Online Tracking Restrictions," in Working Paper, Goethe University Frankfurt.

Müller-Tribbensee, Timo, Klaus Miller, and Bernd Skiera (2022), "Consent-or-Pay Walls," Working Paper, Goethe University Frankfurt.

Neumann, Nico, Catherine.
E. Tucker, and Timothy Whitfield (2019), "Frontiers: How Effective is Third-Party Consumer Profiling? Evidence from Field Studies," Marketing Science, 38 (6), 918-26.

Norberg, Patricia A., Daniel R. Horne, and David A. Horne (2007), "The Privacy Paradox: Personal Information Disclosure Intentions versus Behaviors," Journal of Consumer Affairs, 41 (1), 100-26.

O'Neil, Cathy (2016), Weapons of Math Destruction: How Big Data Increases Inequality and Threatens Democracy: Crown.

Owen, Malcolm (2021), "Ireland Fails in Tackling Big Tech Privacy Complaints," Apple Insiders, <https://appleinsider.com/articles/21/09/13/ireland-fails-in-tackling-big-tech-privacy-complaints>, Sep 13, 2021.

Peukert, Christian, Stefan Bechtold, Michail Batikas, and Tobias Kretschmer (2022), "Regulatory Spillovers and Data Governance: Evidence from the GDPR," Marketing Science, forthcoming.

Pew Research Center (2019), "Americans and Privacy: Concerned, Confused and Feeling Lack of Control Over Their Personal Information," (accessed 20.01.2021, [available at <https://www.pewresearch.org/internet/2019/11/15/americans-and-privacy-concerned-confused-and-feeling-lack-of-control-over-their-personal-information/>].

Pidgeon, David (2016), "Where did the Money Go? Guardian Buys its Own Ad Inventory," in Mediatel News.
<https://mediatel.co.uk/news/2016/10/04/where-did-the-money-go-guardian-buys-its-own-ad-inventory/>.

Presthus, W.
and H.
Sørum (2018), "Are Consumers Concerned About Privacy? An Online Survey Emphasizing the General Data Protection Regulation," Procedia Computer Science, 138, 603--11.

Roth, Yannig (2020), "Google Joining TCF v2... Here's What it Means for Publishers," [available at <https://blog.didomi.io/en/google-joining-tcf-v2-what-it-means-for-publishers>].

Ryan, Johnny (2018), "Report from Dr. Johnny Ryan -- Behavioural Advertising and Personal Data." <https://brave.com/wp-content/uploads/2018/09/Behavioural-advertising-and-personal-data.pdf>.

Ryan, Johnny (2020), "Response to Consultation regarding 'Online Platforms and Digital Advertising'." <https://brave.com/competition-internal-external/>.

Sahni, Navdeep S., Sridhar Narayanan, and Kirthi Kalyanam (2019), "An Experimental Investigation of the Effects of Retargeted Advertising: The Role of Frequency and Timing," Journal of Marketing Research, 56 (3), 401-18.

Sanchez-Rola, I., M. Dell'Amico, P. Kotzias, D. Balzarotti, L. Bilge, P.-A. Vervier, and I.
Santos (2019), "Can I Opt Out Yet? GDPR and the Global Illusion of Cookie Control," in ACM ASIA Conference on Computer and Communications Security.
New York, USA.

Schmitt, Julia (2021), "The Illusion of Control: Control and Convenience on Consent Banners," Working Paper, Goethe University Frankfurt.

Schmitt, Julia, Klaus M. Miller, and Bernd Skiera (2021), "The Impact of Privacy Laws on Online User Behavior," Working Paper, Goethe University Frankfurt.

Shiller, Benjamin, Joel Waldfogel, and Johnny Ryan (2018), "The Effect of Ad Blocking on Website Traffic and Quality," Journal of Economics, 49 (1), 43-64.

Trusov, Michael, Liye Ma, and Zainab Jamal (2016), "Crumbs of the Cookie: User Profiling in Customer-Base Analysis and Behavioral Targeting," Marketing Science, 35 (3), 405-26.

Voisin, Gabriel, Ruth Boardman, Simon Assion, Clara Clark Nevola, Lupe Sampedro, and Ester Vidal (2019), "ICO, CNIL, German and Spanish DPA revised Cookies Guidelines: Convergence and Divergence," Report, <https://iapp.org/resources/article/ico-and-cnil-revised-cookie-guidelines-convergence-and-divergence/>.

Wang, Jun, Weinan Zhang, and Shuai Yuan (2017), "Display Advertising with Real-Time Bidding (RTB) and Behavioural Targeting." arXiv:1610.03013v2 [cs.GT] on July 15, 2017.

Westin, A. F.
(1967), Privacy and Freedom.
New York: Athenaeum.

Wieringa, Jaap, K.P. Kannan, Xiao Ma, Thomas Reutterer, Hans Risseladaa, and Bernd Skiera (2021), "Data Analytics in a Privacy-Concerned World," Journal of Business Research, 122, 915-25.

Wurmser, Yoram (2021), "The Majority of Americans' Mobile Time Spent Takes Place in Apps," [available at <https://www.emarketer.com/content/the-majority-of-americans-mobile-time-spent-takes-place-in-apps>].

Yan, Shunyao, Klaus M. Miller, and Bernd Skiera (2022), "How Does the Adoption of Ad Blockers Affect News Consumption?," Journal of Marketing Research, forthcoming.

Yuan, Shuai, Jun Wang, and Xiaoxue Zhao (2013), "Real-time Bidding for Online Advertising: Measurement and Analysis," in Proceedings of the Seventh International Workshop on Data Mining for Online Advertising.
Chicago, Illinois: ACM.
