---
editor_options: 
  markdown: 
    wrap: sentence
---

#	Information about the Authors

##	Bernd Skiera
Bernd Skiera (skiera@wiwi.uni-frankfurt.de) is a chaired professor of electronic commerce at Goethe University Frankfurt (Germany), a Professorial Fellow at Deakin University (Australia) and a member of the board of the EFL-Data Science Institute and the Schmalenbach-Gesellschaft. His research interests are consumer privacy, marketing analytics, data-driven marketing, electronic commerce, online advertising, SalesTech, MarTech and marketing automation. He received an ERC Advanced Grant to conduct research on consumer privacy on the Internet.

##	Klaus Miller
Klaus Miller (millerk@hec.fr) is an assistant professor of quantitative marketing and Hi!Paris chairholder for the study of data science and artificial intelligence in business and society at HEC Paris (France). During his Ph.D. and as a Post-Doctoral Scholar he has been visiting the Wharton School at the University of Pennsylvania and the Graduate School of Business at Stanford University. His research interests meet at the interface of empirical quantitative marketing, management economics, and information systems. Specifically, his research concerns pricing, advertising, and customer management topics in the digital economy. Recently, Klaus has developed an research interest in online consumer privacy.


##	Yuxi Jin
Yuxi Jin (y.jin@wiwi.uni-frankfurt.de) is a doctoral student at Goethe University Frankfurt (Germany). Her research interests are consumer privacy and regulation, online advertising, and data analytics.

##	Lennart Kraft
Lennart Kraft (Lennart.kraft@wiwi.uni-frankfurt.de) is a doctoral student in Quantitative Economics at Goethe University Frankfurt (Germany) and senior data manager at Financial Research Data Infrastructure of Leibniz Institute for Financial Research SAFE. His research interests are digital economics, online advertising, online consumer privacy, and, more broadly, data analytics, data protection, and data management.

##	René Laub
René Laub (rlaub@wiwi.uni-frankfurt.de) is a doctoral student at Goethe University Frankfurt (Germany). His research interests are at the interface of marketing and information systems research, focusing on consumer privacy, digital marketing, and MarTech. 

##	Julia Schmitt
Julia Schmitt (schmitt@wiwi.uni-frankfurt.de) was a doctoral student at Goethe University Frankfurt (Germany). Her research interests are consumer privacy, privacy regulations, consent management and data analytics. 
